#!/bin/sh
#
# prompt for a password via bemenu
# generate new password if it doesn't exist
# then type the selected password via wtype

name=$(pa l | bemenu -c -W 0.2 -l 20 "$@") || exit
{ pa s "$name" || { printf y | pa a "$name" >/dev/null && pa s "$name"; }; } |
    head -n 1 | tr -d '\n' | wtype -
