#!/bin/sh
#
# prompt for a password via dmenu
# generate new password if it doesn't exist
# then type the selected password via xdotool

name=$(pa l | dmenu "$@") || exit
{ pa s "$name" || { printf y | pa a "$name" >/dev/null && pa s "$name"; }; } |
    head -n 1 | tr -d '\n' | xdotool type --clearmodifiers --file -
