#!/bin/sh
#
# prompt for a password via dmenu
# then type the selected password via xdotool

name=$(pa list | dmenu "$@")
pa show "$name" | head -n 1 | tr -d '\n' | xdotool type --clearmodifiers --file -
