#!/bin/sh
#
# prompt for a password via fuzzel
# generate new password if it doesn't exist
# then type the selected password via wtype

name=$(pa list | fuzzel -dmenu "$@") || exit
{ pa show "$name" || { printf y | pa add "$name" >/dev/null && pa show "$name"; }; } |
    head -n 1 | tr -d '\n' | wtype -
