#!/bin/sh
#
# prompt for a password via fuzzel
# generate new password if it doesn't exist
# then type the selected password via wtype

name=$(pa l | fuzzel -dmenu "$@") || exit
{ pa s "$name" || { printf y | pa a "$name" >/dev/null && pa s "$name"; }; } |
    head -n 1 | tr -d '\n' | wtype -
