#!/bin/sh
#
# prompt for a password via rofi
# then type the selected password via xdotool

name=$(pa list | rofi -dmenu -i "$@")
pa show "$name" | head -n 1 | tr -d '\n' | xdotool type --clearmodifiers --file -
